insert into public.stickers (id, team_code, team_name, player_name, position, rarity, is_starter, role, number_code) values
(1, 'ARG', 'Argentina', 'Emiliano Martinez', 'ARQ', 'epica', true, 'player', 'ARG-01'),
(2, 'ARG', 'Argentina', 'Nahuel Molina', 'LD', 'epica', true, 'player', 'ARG-02'),
(3, 'ARG', 'Argentina', 'Cristian Romero', 'DFC', 'epica', true, 'player', 'ARG-03'),
(4, 'ARG', 'Argentina', 'Nicolas Otamendi', 'DFC', 'epica', true, 'player', 'ARG-04'),
(5, 'ARG', 'Argentina', 'Nicolas Tagliafico', 'LI', 'epica', true, 'player', 'ARG-05'),
(6, 'ARG', 'Argentina', 'Rodrigo De Paul', 'MC', 'rara', true, 'player', 'ARG-06'),
(7, 'ARG', 'Argentina', 'Enzo Fernandez', 'MC', 'rara', true, 'player', 'ARG-07'),
(8, 'ARG', 'Argentina', 'Alexis Mac Allister', 'MC', 'rara', true, 'player', 'ARG-08'),
(9, 'ARG', 'Argentina', 'Lionel Messi', 'ED', 'rara', true, 'player', 'ARG-09'),
(10, 'ARG', 'Argentina', 'Julian Alvarez', 'DC', 'rara', true, 'player', 'ARG-10'),
(11, 'ARG', 'Argentina', 'Lautaro Martinez', 'EI', 'rara', true, 'player', 'ARG-11'),
(12, 'ARG', 'Argentina', 'Geronimo Rulli', 'ARQ', 'comun', false, 'player', 'ARG-12'),
(13, 'ARG', 'Argentina', 'Walter Benitez', 'ARQ', 'comun', false, 'player', 'ARG-13'),
(14, 'ARG', 'Argentina', 'Gonzalo Montiel', 'DEF', 'comun', false, 'player', 'ARG-14'),
(15, 'ARG', 'Argentina', 'Lisandro Martinez', 'DEF', 'comun', false, 'player', 'ARG-15'),
(16, 'ARG', 'Argentina', 'Marcos Senesi', 'DEF', 'comun', false, 'player', 'ARG-16'),
(17, 'ARG', 'Argentina', 'Leonardo Balerdi', 'DEF', 'comun', false, 'player', 'ARG-17'),
(18, 'ARG', 'Argentina', 'Valentin Barco', 'DEF', 'comun', false, 'player', 'ARG-18'),
(19, 'ARG', 'Argentina', 'Leandro Paredes', 'MED', 'comun', false, 'player', 'ARG-19'),
(20, 'ARG', 'Argentina', 'Exequiel Palacios', 'MED', 'comun', false, 'player', 'ARG-20'),
(21, 'ARG', 'Argentina', 'Giovani Lo Celso', 'MED', 'comun', false, 'player', 'ARG-21'),
(22, 'ARG', 'Argentina', 'Thiago Almada', 'MED', 'comun', false, 'player', 'ARG-22'),
(23, 'ARG', 'Argentina', 'Nicolas Paz', 'MED', 'comun', false, 'player', 'ARG-23'),
(24, 'ARG', 'Argentina', 'Alejandro Garnacho', 'DEL', 'comun', false, 'player', 'ARG-24'),
(25, 'ARG', 'Argentina', 'Nico Gonzalez', 'DEL', 'comun', false, 'player', 'ARG-25'),
(26, 'ARG', 'Argentina', 'Angel Correa', 'DEL', 'comun', false, 'player', 'ARG-26'),
(27, 'ARG', 'Argentina', 'Lionel Scaloni', 'DT', 'legendaria', true, 'coach', 'ARG-27'),
(28, 'BRA', 'Brasil', 'Alisson', 'ARQ', 'epica', true, 'player', 'BRA-01'),
(29, 'BRA', 'Brasil', 'Vanderson', 'LD', 'epica', true, 'player', 'BRA-02'),
(30, 'BRA', 'Brasil', 'Marquinhos', 'DFC', 'epica', true, 'player', 'BRA-03'),
(31, 'BRA', 'Brasil', 'Gabriel Magalhaes', 'DFC', 'epica', true, 'player', 'BRA-04'),
(32, 'BRA', 'Brasil', 'Guilherme Arana', 'LI', 'epica', true, 'player', 'BRA-05'),
(33, 'BRA', 'Brasil', 'Bruno Guimaraes', 'MC', 'rara', true, 'player', 'BRA-06'),
(34, 'BRA', 'Brasil', 'Joao Gomes', 'MC', 'rara', true, 'player', 'BRA-07'),
(35, 'BRA', 'Brasil', 'Lucas Paqueta', 'MC', 'rara', true, 'player', 'BRA-08'),
(36, 'BRA', 'Brasil', 'Rodrygo', 'ED', 'rara', true, 'player', 'BRA-09'),
(37, 'BRA', 'Brasil', 'Endrick', 'DC', 'rara', true, 'player', 'BRA-10'),
(38, 'BRA', 'Brasil', 'Vinicius Junior', 'EI', 'rara', true, 'player', 'BRA-11'),
(39, 'BRA', 'Brasil', 'Ederson', 'ARQ', 'comun', false, 'player', 'BRA-12'),
(40, 'BRA', 'Brasil', 'Bento', 'ARQ', 'comun', false, 'player', 'BRA-13'),
(41, 'BRA', 'Brasil', 'Danilo', 'DEF', 'comun', false, 'player', 'BRA-14'),
(42, 'BRA', 'Brasil', 'Bremer', 'DEF', 'comun', false, 'player', 'BRA-15'),
(43, 'BRA', 'Brasil', 'Beraldo', 'DEF', 'comun', false, 'player', 'BRA-16'),
(44, 'BRA', 'Brasil', 'Wendell', 'DEF', 'comun', false, 'player', 'BRA-17'),
(45, 'BRA', 'Brasil', 'Carlos Augusto', 'DEF', 'comun', false, 'player', 'BRA-18'),
(46, 'BRA', 'Brasil', 'Douglas Luiz', 'MED', 'comun', false, 'player', 'BRA-19'),
(47, 'BRA', 'Brasil', 'Andre', 'MED', 'comun', false, 'player', 'BRA-20'),
(48, 'BRA', 'Brasil', 'Joelinton', 'MED', 'comun', false, 'player', 'BRA-21'),
(49, 'BRA', 'Brasil', 'Andreas Pereira', 'MED', 'comun', false, 'player', 'BRA-22'),
(50, 'BRA', 'Brasil', 'Raphael Veiga', 'MED', 'comun', false, 'player', 'BRA-23'),
(51, 'BRA', 'Brasil', 'Raphinha', 'DEL', 'comun', false, 'player', 'BRA-24'),
(52, 'BRA', 'Brasil', 'Savinho', 'DEL', 'comun', false, 'player', 'BRA-25'),
(53, 'BRA', 'Brasil', 'Gabriel Martinelli', 'DEL', 'comun', false, 'player', 'BRA-26'),
(54, 'BRA', 'Brasil', 'Carlo Ancelotti', 'DT', 'legendaria', true, 'coach', 'BRA-27'),
(55, 'URU', 'Uruguay', 'Sergio Rochet', 'ARQ', 'epica', true, 'player', 'URU-01'),
(56, 'URU', 'Uruguay', 'Nahitan Nandez', 'LD', 'epica', true, 'player', 'URU-02'),
(57, 'URU', 'Uruguay', 'Jose Maria Gimenez', 'DFC', 'epica', true, 'player', 'URU-03'),
(58, 'URU', 'Uruguay', 'Ronald Araujo', 'DFC', 'epica', true, 'player', 'URU-04'),
(59, 'URU', 'Uruguay', 'Mathias Olivera', 'LI', 'epica', true, 'player', 'URU-05'),
(60, 'URU', 'Uruguay', 'Federico Valverde', 'MC', 'rara', true, 'player', 'URU-06'),
(61, 'URU', 'Uruguay', 'Manuel Ugarte', 'MC', 'rara', true, 'player', 'URU-07'),
(62, 'URU', 'Uruguay', 'Nicolas De La Cruz', 'MC', 'rara', true, 'player', 'URU-08'),
(63, 'URU', 'Uruguay', 'Facundo Pellistri', 'ED', 'rara', true, 'player', 'URU-09'),
(64, 'URU', 'Uruguay', 'Darwin Nunez', 'DC', 'rara', true, 'player', 'URU-10'),
(65, 'URU', 'Uruguay', 'Maximiliano Araujo', 'EI', 'rara', true, 'player', 'URU-11'),
(66, 'URU', 'Uruguay', 'Santiago Mele', 'ARQ', 'comun', false, 'player', 'URU-12'),
(67, 'URU', 'Uruguay', 'Franco Israel', 'ARQ', 'comun', false, 'player', 'URU-13'),
(68, 'URU', 'Uruguay', 'Guillermo Varela', 'DEF', 'comun', false, 'player', 'URU-14'),
(69, 'URU', 'Uruguay', 'Sebastian Caceres', 'DEF', 'comun', false, 'player', 'URU-15'),
(70, 'URU', 'Uruguay', 'Matias Vina', 'DEF', 'comun', false, 'player', 'URU-16'),
(71, 'URU', 'Uruguay', 'Santiago Bueno', 'DEF', 'comun', false, 'player', 'URU-17'),
(72, 'URU', 'Uruguay', 'Jose Luis Rodriguez', 'DEF', 'comun', false, 'player', 'URU-18'),
(73, 'URU', 'Uruguay', 'Rodrigo Bentancur', 'MED', 'comun', false, 'player', 'URU-19'),
(74, 'URU', 'Uruguay', 'Giorgian De Arrascaeta', 'MED', 'comun', false, 'player', 'URU-20'),
(75, 'URU', 'Uruguay', 'Nicolas Fonseca', 'MED', 'comun', false, 'player', 'URU-21'),
(76, 'URU', 'Uruguay', 'Agustin Canobbio', 'MED', 'comun', false, 'player', 'URU-22'),
(77, 'URU', 'Uruguay', 'Brian Rodriguez', 'DEL', 'comun', false, 'player', 'URU-23'),
(78, 'URU', 'Uruguay', 'Cristian Olivera', 'DEL', 'comun', false, 'player', 'URU-24'),
(79, 'URU', 'Uruguay', 'Luciano Rodriguez', 'DEL', 'comun', false, 'player', 'URU-25'),
(80, 'URU', 'Uruguay', 'Luis Suarez', 'DEL', 'comun', false, 'player', 'URU-26'),
(81, 'URU', 'Uruguay', 'Marcelo Bielsa', 'DT', 'legendaria', true, 'coach', 'URU-27'),
(82, 'FRA', 'Francia', 'Mike Maignan', 'ARQ', 'epica', true, 'player', 'FRA-01'),
(83, 'FRA', 'Francia', 'Jules Kounde', 'LD', 'epica', true, 'player', 'FRA-02'),
(84, 'FRA', 'Francia', 'William Saliba', 'DFC', 'epica', true, 'player', 'FRA-03'),
(85, 'FRA', 'Francia', 'Dayot Upamecano', 'DFC', 'epica', true, 'player', 'FRA-04'),
(86, 'FRA', 'Francia', 'Theo Hernandez', 'LI', 'epica', true, 'player', 'FRA-05'),
(87, 'FRA', 'Francia', 'Aurelien Tchouameni', 'MC', 'rara', true, 'player', 'FRA-06'),
(88, 'FRA', 'Francia', 'Eduardo Camavinga', 'MC', 'rara', true, 'player', 'FRA-07'),
(89, 'FRA', 'Francia', 'Adrien Rabiot', 'MC', 'rara', true, 'player', 'FRA-08'),
(90, 'FRA', 'Francia', 'Ousmane Dembele', 'ED', 'rara', true, 'player', 'FRA-09'),
(91, 'FRA', 'Francia', 'Kylian Mbappe', 'DC', 'rara', true, 'player', 'FRA-10'),
(92, 'FRA', 'Francia', 'Bradley Barcola', 'EI', 'rara', true, 'player', 'FRA-11'),
(93, 'FRA', 'Francia', 'Brice Samba', 'ARQ', 'comun', false, 'player', 'FRA-12'),
(94, 'FRA', 'Francia', 'Lucas Chevalier', 'ARQ', 'comun', false, 'player', 'FRA-13'),
(95, 'FRA', 'Francia', 'Benjamin Pavard', 'DEF', 'comun', false, 'player', 'FRA-14'),
(96, 'FRA', 'Francia', 'Ibrahima Konate', 'DEF', 'comun', false, 'player', 'FRA-15'),
(97, 'FRA', 'Francia', 'Lucas Hernandez', 'DEF', 'comun', false, 'player', 'FRA-16'),
(98, 'FRA', 'Francia', 'Jean-Clair Todibo', 'DEF', 'comun', false, 'player', 'FRA-17'),
(99, 'FRA', 'Francia', 'Jonathan Clauss', 'DEF', 'comun', false, 'player', 'FRA-18'),
(100, 'FRA', 'Francia', 'Warren Zaire-Emery', 'MED', 'comun', false, 'player', 'FRA-19'),
(101, 'FRA', 'Francia', 'Youssouf Fofana', 'MED', 'comun', false, 'player', 'FRA-20'),
(102, 'FRA', 'Francia', 'Matteo Guendouzi', 'MED', 'comun', false, 'player', 'FRA-21'),
(103, 'FRA', 'Francia', 'Antoine Griezmann', 'MED', 'comun', false, 'player', 'FRA-22'),
(104, 'FRA', 'Francia', 'Michael Olise', 'DEL', 'comun', false, 'player', 'FRA-23'),
(105, 'FRA', 'Francia', 'Kingsley Coman', 'DEL', 'comun', false, 'player', 'FRA-24'),
(106, 'FRA', 'Francia', 'Marcus Thuram', 'DEL', 'comun', false, 'player', 'FRA-25'),
(107, 'FRA', 'Francia', 'Randal Kolo Muani', 'DEL', 'comun', false, 'player', 'FRA-26'),
(108, 'FRA', 'Francia', 'Didier Deschamps', 'DT', 'legendaria', true, 'coach', 'FRA-27'),
(109, 'ESP', 'Espana', 'Unai Simon', 'ARQ', 'epica', true, 'player', 'ESP-01'),
(110, 'ESP', 'Espana', 'Dani Carvajal', 'LD', 'epica', true, 'player', 'ESP-02'),
(111, 'ESP', 'Espana', 'Robin Le Normand', 'DFC', 'epica', true, 'player', 'ESP-03'),
(112, 'ESP', 'Espana', 'Pau Cubarsi', 'DFC', 'epica', true, 'player', 'ESP-04'),
(113, 'ESP', 'Espana', 'Marc Cucurella', 'LI', 'epica', true, 'player', 'ESP-05'),
(114, 'ESP', 'Espana', 'Rodri', 'MC', 'rara', true, 'player', 'ESP-06'),
(115, 'ESP', 'Espana', 'Pedri', 'MC', 'rara', true, 'player', 'ESP-07'),
(116, 'ESP', 'Espana', 'Fabian Ruiz', 'MC', 'rara', true, 'player', 'ESP-08'),
(117, 'ESP', 'Espana', 'Lamine Yamal', 'ED', 'rara', true, 'player', 'ESP-09'),
(118, 'ESP', 'Espana', 'Alvaro Morata', 'DC', 'rara', true, 'player', 'ESP-10'),
(119, 'ESP', 'Espana', 'Nico Williams', 'EI', 'rara', true, 'player', 'ESP-11'),
(120, 'ESP', 'Espana', 'David Raya', 'ARQ', 'comun', false, 'player', 'ESP-12'),
(121, 'ESP', 'Espana', 'Alex Remiro', 'ARQ', 'comun', false, 'player', 'ESP-13'),
(122, 'ESP', 'Espana', 'Pedro Porro', 'DEF', 'comun', false, 'player', 'ESP-14'),
(123, 'ESP', 'Espana', 'Aymeric Laporte', 'DEF', 'comun', false, 'player', 'ESP-15'),
(124, 'ESP', 'Espana', 'Daniel Vivian', 'DEF', 'comun', false, 'player', 'ESP-16'),
(125, 'ESP', 'Espana', 'Alejandro Grimaldo', 'DEF', 'comun', false, 'player', 'ESP-17'),
(126, 'ESP', 'Espana', 'Jesus Navas', 'DEF', 'comun', false, 'player', 'ESP-18'),
(127, 'ESP', 'Espana', 'Martin Zubimendi', 'MED', 'comun', false, 'player', 'ESP-19'),
(128, 'ESP', 'Espana', 'Mikel Merino', 'MED', 'comun', false, 'player', 'ESP-20'),
(129, 'ESP', 'Espana', 'Gavi', 'MED', 'comun', false, 'player', 'ESP-21'),
(130, 'ESP', 'Espana', 'Dani Olmo', 'MED', 'comun', false, 'player', 'ESP-22'),
(131, 'ESP', 'Espana', 'Mikel Oyarzabal', 'DEL', 'comun', false, 'player', 'ESP-23'),
(132, 'ESP', 'Espana', 'Ferran Torres', 'DEL', 'comun', false, 'player', 'ESP-24'),
(133, 'ESP', 'Espana', 'Ayoze Perez', 'DEL', 'comun', false, 'player', 'ESP-25'),
(134, 'ESP', 'Espana', 'Joselu', 'DEL', 'comun', false, 'player', 'ESP-26'),
(135, 'ESP', 'Espana', 'Luis de la Fuente', 'DT', 'legendaria', true, 'coach', 'ESP-27'),
(136, 'ING', 'Inglaterra', 'Jordan Pickford', 'ARQ', 'epica', true, 'player', 'ING-01'),
(137, 'ING', 'Inglaterra', 'Kyle Walker', 'LD', 'epica', true, 'player', 'ING-02'),
(138, 'ING', 'Inglaterra', 'John Stones', 'DFC', 'epica', true, 'player', 'ING-03'),
(139, 'ING', 'Inglaterra', 'Marc Guehi', 'DFC', 'epica', true, 'player', 'ING-04'),
(140, 'ING', 'Inglaterra', 'Luke Shaw', 'LI', 'epica', true, 'player', 'ING-05'),
(141, 'ING', 'Inglaterra', 'Declan Rice', 'MC', 'rara', true, 'player', 'ING-06'),
(142, 'ING', 'Inglaterra', 'Jude Bellingham', 'MC', 'rara', true, 'player', 'ING-07'),
(143, 'ING', 'Inglaterra', 'Bukayo Saka', 'ED', 'rara', true, 'player', 'ING-08'),
(144, 'ING', 'Inglaterra', 'Cole Palmer', 'MCO', 'rara', true, 'player', 'ING-09'),
(145, 'ING', 'Inglaterra', 'Phil Foden', 'EI', 'rara', true, 'player', 'ING-10'),
(146, 'ING', 'Inglaterra', 'Harry Kane', 'DC', 'rara', true, 'player', 'ING-11'),
(147, 'ING', 'Inglaterra', 'Aaron Ramsdale', 'ARQ', 'comun', false, 'player', 'ING-12'),
(148, 'ING', 'Inglaterra', 'Dean Henderson', 'ARQ', 'comun', false, 'player', 'ING-13'),
(149, 'ING', 'Inglaterra', 'Trent Alexander-Arnold', 'DEF', 'comun', false, 'player', 'ING-14'),
(150, 'ING', 'Inglaterra', 'Fikayo Tomori', 'DEF', 'comun', false, 'player', 'ING-15'),
(151, 'ING', 'Inglaterra', 'Levi Colwill', 'DEF', 'comun', false, 'player', 'ING-16'),
(152, 'ING', 'Inglaterra', 'Lewis Hall', 'DEF', 'comun', false, 'player', 'ING-17'),
(153, 'ING', 'Inglaterra', 'Kieran Trippier', 'DEF', 'comun', false, 'player', 'ING-18'),
(154, 'ING', 'Inglaterra', 'Kobbie Mainoo', 'MED', 'comun', false, 'player', 'ING-19'),
(155, 'ING', 'Inglaterra', 'Conor Gallagher', 'MED', 'comun', false, 'player', 'ING-20'),
(156, 'ING', 'Inglaterra', 'James Maddison', 'MED', 'comun', false, 'player', 'ING-21'),
(157, 'ING', 'Inglaterra', 'Adam Wharton', 'MED', 'comun', false, 'player', 'ING-22'),
(158, 'ING', 'Inglaterra', 'Anthony Gordon', 'DEL', 'comun', false, 'player', 'ING-23'),
(159, 'ING', 'Inglaterra', 'Ollie Watkins', 'DEL', 'comun', false, 'player', 'ING-24'),
(160, 'ING', 'Inglaterra', 'Jarrod Bowen', 'DEL', 'comun', false, 'player', 'ING-25'),
(161, 'ING', 'Inglaterra', 'Marcus Rashford', 'DEL', 'comun', false, 'player', 'ING-26'),
(162, 'ING', 'Inglaterra', 'Thomas Tuchel', 'DT', 'legendaria', true, 'coach', 'ING-27'),
(163, 'ALE', 'Alemania', 'Marc-Andre ter Stegen', 'ARQ', 'epica', true, 'player', 'ALE-01'),
(164, 'ALE', 'Alemania', 'Joshua Kimmich', 'LD', 'epica', true, 'player', 'ALE-02'),
(165, 'ALE', 'Alemania', 'Antonio Rudiger', 'DFC', 'epica', true, 'player', 'ALE-03'),
(166, 'ALE', 'Alemania', 'Jonathan Tah', 'DFC', 'epica', true, 'player', 'ALE-04'),
(167, 'ALE', 'Alemania', 'Maximilian Mittelstadt', 'LI', 'epica', true, 'player', 'ALE-05'),
(168, 'ALE', 'Alemania', 'Robert Andrich', 'MC', 'rara', true, 'player', 'ALE-06'),
(169, 'ALE', 'Alemania', 'Pascal Gross', 'MC', 'rara', true, 'player', 'ALE-07'),
(170, 'ALE', 'Alemania', 'Leroy Sane', 'ED', 'rara', true, 'player', 'ALE-08'),
(171, 'ALE', 'Alemania', 'Jamal Musiala', 'MCO', 'rara', true, 'player', 'ALE-09'),
(172, 'ALE', 'Alemania', 'Florian Wirtz', 'EI', 'rara', true, 'player', 'ALE-10'),
(173, 'ALE', 'Alemania', 'Kai Havertz', 'DC', 'rara', true, 'player', 'ALE-11'),
(174, 'ALE', 'Alemania', 'Manuel Neuer', 'ARQ', 'comun', false, 'player', 'ALE-12'),
(175, 'ALE', 'Alemania', 'Alexander Nubel', 'ARQ', 'comun', false, 'player', 'ALE-13'),
(176, 'ALE', 'Alemania', 'Benjamin Henrichs', 'DEF', 'comun', false, 'player', 'ALE-14'),
(177, 'ALE', 'Alemania', 'Nico Schlotterbeck', 'DEF', 'comun', false, 'player', 'ALE-15'),
(178, 'ALE', 'Alemania', 'Waldemar Anton', 'DEF', 'comun', false, 'player', 'ALE-16'),
(179, 'ALE', 'Alemania', 'David Raum', 'DEF', 'comun', false, 'player', 'ALE-17'),
(180, 'ALE', 'Alemania', 'Robin Koch', 'DEF', 'comun', false, 'player', 'ALE-18'),
(181, 'ALE', 'Alemania', 'Aleksandar Pavlovic', 'MED', 'comun', false, 'player', 'ALE-19'),
(182, 'ALE', 'Alemania', 'Emre Can', 'MED', 'comun', false, 'player', 'ALE-20'),
(183, 'ALE', 'Alemania', 'Leon Goretzka', 'MED', 'comun', false, 'player', 'ALE-21'),
(184, 'ALE', 'Alemania', 'Chris Fuhrich', 'MED', 'comun', false, 'player', 'ALE-22'),
(185, 'ALE', 'Alemania', 'Niclas Fullkrug', 'DEL', 'comun', false, 'player', 'ALE-23'),
(186, 'ALE', 'Alemania', 'Deniz Undav', 'DEL', 'comun', false, 'player', 'ALE-24'),
(187, 'ALE', 'Alemania', 'Karim Adeyemi', 'DEL', 'comun', false, 'player', 'ALE-25'),
(188, 'ALE', 'Alemania', 'Maximilian Beier', 'DEL', 'comun', false, 'player', 'ALE-26'),
(189, 'ALE', 'Alemania', 'Julian Nagelsmann', 'DT', 'legendaria', true, 'coach', 'ALE-27'),
(190, 'POR', 'Portugal', 'Diogo Costa', 'ARQ', 'epica', true, 'player', 'POR-01'),
(191, 'POR', 'Portugal', 'Joao Cancelo', 'LD', 'epica', true, 'player', 'POR-02'),
(192, 'POR', 'Portugal', 'Ruben Dias', 'DFC', 'epica', true, 'player', 'POR-03'),
(193, 'POR', 'Portugal', 'Goncalo Inacio', 'DFC', 'epica', true, 'player', 'POR-04'),
(194, 'POR', 'Portugal', 'Nuno Mendes', 'LI', 'epica', true, 'player', 'POR-05'),
(195, 'POR', 'Portugal', 'Joao Palhinha', 'MC', 'rara', true, 'player', 'POR-06'),
(196, 'POR', 'Portugal', 'Vitinha', 'MC', 'rara', true, 'player', 'POR-07'),
(197, 'POR', 'Portugal', 'Bruno Fernandes', 'MC', 'rara', true, 'player', 'POR-08'),
(198, 'POR', 'Portugal', 'Bernardo Silva', 'ED', 'rara', true, 'player', 'POR-09'),
(199, 'POR', 'Portugal', 'Goncalo Ramos', 'DC', 'rara', true, 'player', 'POR-10'),
(200, 'POR', 'Portugal', 'Rafael Leao', 'EI', 'rara', true, 'player', 'POR-11'),
(201, 'POR', 'Portugal', 'Jose Sa', 'ARQ', 'comun', false, 'player', 'POR-12'),
(202, 'POR', 'Portugal', 'Rui Patricio', 'ARQ', 'comun', false, 'player', 'POR-13'),
(203, 'POR', 'Portugal', 'Diogo Dalot', 'DEF', 'comun', false, 'player', 'POR-14'),
(204, 'POR', 'Portugal', 'Antonio Silva', 'DEF', 'comun', false, 'player', 'POR-15'),
(205, 'POR', 'Portugal', 'Danilo Pereira', 'DEF', 'comun', false, 'player', 'POR-16'),
(206, 'POR', 'Portugal', 'Raphael Guerreiro', 'DEF', 'comun', false, 'player', 'POR-17'),
(207, 'POR', 'Portugal', 'Nelson Semedo', 'DEF', 'comun', false, 'player', 'POR-18'),
(208, 'POR', 'Portugal', 'Joao Neves', 'MED', 'comun', false, 'player', 'POR-19'),
(209, 'POR', 'Portugal', 'Ruben Neves', 'MED', 'comun', false, 'player', 'POR-20'),
(210, 'POR', 'Portugal', 'Matheus Nunes', 'MED', 'comun', false, 'player', 'POR-21'),
(211, 'POR', 'Portugal', 'Otavio', 'MED', 'comun', false, 'player', 'POR-22'),
(212, 'POR', 'Portugal', 'Cristiano Ronaldo', 'DEL', 'comun', false, 'player', 'POR-23'),
(213, 'POR', 'Portugal', 'Joao Felix', 'DEL', 'comun', false, 'player', 'POR-24'),
(214, 'POR', 'Portugal', 'Francisco Conceicao', 'DEL', 'comun', false, 'player', 'POR-25'),
(215, 'POR', 'Portugal', 'Pedro Neto', 'DEL', 'comun', false, 'player', 'POR-26'),
(216, 'POR', 'Portugal', 'Roberto Martinez', 'DT', 'legendaria', true, 'coach', 'POR-27'),
(217, 'NED', 'Paises Bajos', 'Bart Verbruggen', 'ARQ', 'epica', true, 'player', 'NED-01'),
(218, 'NED', 'Paises Bajos', 'Denzel Dumfries', 'LD', 'epica', true, 'player', 'NED-02'),
(219, 'NED', 'Paises Bajos', 'Virgil van Dijk', 'DFC', 'epica', true, 'player', 'NED-03'),
(220, 'NED', 'Paises Bajos', 'Nathan Ake', 'DFC', 'epica', true, 'player', 'NED-04'),
(221, 'NED', 'Paises Bajos', 'Micky van de Ven', 'LI', 'epica', true, 'player', 'NED-05'),
(222, 'NED', 'Paises Bajos', 'Frenkie de Jong', 'MC', 'rara', true, 'player', 'NED-06'),
(223, 'NED', 'Paises Bajos', 'Tijjani Reijnders', 'MC', 'rara', true, 'player', 'NED-07'),
(224, 'NED', 'Paises Bajos', 'Xavi Simons', 'MC', 'rara', true, 'player', 'NED-08'),
(225, 'NED', 'Paises Bajos', 'Donyell Malen', 'ED', 'rara', true, 'player', 'NED-09'),
(226, 'NED', 'Paises Bajos', 'Memphis Depay', 'DC', 'rara', true, 'player', 'NED-10'),
(227, 'NED', 'Paises Bajos', 'Cody Gakpo', 'EI', 'rara', true, 'player', 'NED-11'),
(228, 'NED', 'Paises Bajos', 'Mark Flekken', 'ARQ', 'comun', false, 'player', 'NED-12'),
(229, 'NED', 'Paises Bajos', 'Justin Bijlow', 'ARQ', 'comun', false, 'player', 'NED-13'),
(230, 'NED', 'Paises Bajos', 'Jeremie Frimpong', 'DEF', 'comun', false, 'player', 'NED-14'),
(231, 'NED', 'Paises Bajos', 'Matthijs de Ligt', 'DEF', 'comun', false, 'player', 'NED-15'),
(232, 'NED', 'Paises Bajos', 'Stefan de Vrij', 'DEF', 'comun', false, 'player', 'NED-16'),
(233, 'NED', 'Paises Bajos', 'Jorrel Hato', 'DEF', 'comun', false, 'player', 'NED-17'),
(234, 'NED', 'Paises Bajos', 'Daley Blind', 'DEF', 'comun', false, 'player', 'NED-18'),
(235, 'NED', 'Paises Bajos', 'Jerdy Schouten', 'MED', 'comun', false, 'player', 'NED-19'),
(236, 'NED', 'Paises Bajos', 'Ryan Gravenberch', 'MED', 'comun', false, 'player', 'NED-20'),
(237, 'NED', 'Paises Bajos', 'Teun Koopmeiners', 'MED', 'comun', false, 'player', 'NED-21'),
(238, 'NED', 'Paises Bajos', 'Joey Veerman', 'MED', 'comun', false, 'player', 'NED-22'),
(239, 'NED', 'Paises Bajos', 'Brian Brobbey', 'DEL', 'comun', false, 'player', 'NED-23'),
(240, 'NED', 'Paises Bajos', 'Noa Lang', 'DEL', 'comun', false, 'player', 'NED-24'),
(241, 'NED', 'Paises Bajos', 'Steven Bergwijn', 'DEL', 'comun', false, 'player', 'NED-25'),
(242, 'NED', 'Paises Bajos', 'Justin Kluivert', 'DEL', 'comun', false, 'player', 'NED-26'),
(243, 'NED', 'Paises Bajos', 'Ronald Koeman', 'DT', 'legendaria', true, 'coach', 'NED-27'),
(244, 'JPN', 'Japon', 'Zion Suzuki', 'ARQ', 'epica', true, 'player', 'JPN-01'),
(245, 'JPN', 'Japon', 'Yukinari Sugawara', 'LD', 'epica', true, 'player', 'JPN-02'),
(246, 'JPN', 'Japon', 'Takehiro Tomiyasu', 'DFC', 'epica', true, 'player', 'JPN-03'),
(247, 'JPN', 'Japon', 'Ko Itakura', 'DFC', 'epica', true, 'player', 'JPN-04'),
(248, 'JPN', 'Japon', 'Hiroki Ito', 'LI', 'epica', true, 'player', 'JPN-05'),
(249, 'JPN', 'Japon', 'Wataru Endo', 'MC', 'rara', true, 'player', 'JPN-06'),
(250, 'JPN', 'Japon', 'Hidemasa Morita', 'MC', 'rara', true, 'player', 'JPN-07'),
(251, 'JPN', 'Japon', 'Takefusa Kubo', 'ED', 'rara', true, 'player', 'JPN-08'),
(252, 'JPN', 'Japon', 'Daichi Kamada', 'MCO', 'rara', true, 'player', 'JPN-09'),
(253, 'JPN', 'Japon', 'Kaoru Mitoma', 'EI', 'rara', true, 'player', 'JPN-10'),
(254, 'JPN', 'Japon', 'Ayase Ueda', 'DC', 'rara', true, 'player', 'JPN-11'),
(255, 'JPN', 'Japon', 'Keisuke Osako', 'ARQ', 'comun', false, 'player', 'JPN-12'),
(256, 'JPN', 'Japon', 'Daniel Schmidt', 'ARQ', 'comun', false, 'player', 'JPN-13'),
(257, 'JPN', 'Japon', 'Seiya Maikuma', 'DEF', 'comun', false, 'player', 'JPN-14'),
(258, 'JPN', 'Japon', 'Koki Machida', 'DEF', 'comun', false, 'player', 'JPN-15'),
(259, 'JPN', 'Japon', 'Takehiro Watanabe', 'DEF', 'comun', false, 'player', 'JPN-16'),
(260, 'JPN', 'Japon', 'Yuta Nakayama', 'DEF', 'comun', false, 'player', 'JPN-17'),
(261, 'JPN', 'Japon', 'Yuto Nagatomo', 'DEF', 'comun', false, 'player', 'JPN-18'),
(262, 'JPN', 'Japon', 'Ao Tanaka', 'MED', 'comun', false, 'player', 'JPN-19'),
(263, 'JPN', 'Japon', 'Reo Hatate', 'MED', 'comun', false, 'player', 'JPN-20'),
(264, 'JPN', 'Japon', 'Ritsu Doan', 'MED', 'comun', false, 'player', 'JPN-21'),
(265, 'JPN', 'Japon', 'Takumi Minamino', 'MED', 'comun', false, 'player', 'JPN-22'),
(266, 'JPN', 'Japon', 'Junya Ito', 'DEL', 'comun', false, 'player', 'JPN-23'),
(267, 'JPN', 'Japon', 'Kyogo Furuhashi', 'DEL', 'comun', false, 'player', 'JPN-24'),
(268, 'JPN', 'Japon', 'Daizen Maeda', 'DEL', 'comun', false, 'player', 'JPN-25'),
(269, 'JPN', 'Japon', 'Takuma Asano', 'DEL', 'comun', false, 'player', 'JPN-26'),
(270, 'JPN', 'Japon', 'Hajime Moriyasu', 'DT', 'legendaria', true, 'coach', 'JPN-27'),
(271, 'MEX', 'Mexico', 'Luis Malagon', 'ARQ', 'epica', true, 'player', 'MEX-01'),
(272, 'MEX', 'Mexico', 'Jorge Sanchez', 'LD', 'epica', true, 'player', 'MEX-02'),
(273, 'MEX', 'Mexico', 'Cesar Montes', 'DFC', 'epica', true, 'player', 'MEX-03'),
(274, 'MEX', 'Mexico', 'Johan Vasquez', 'DFC', 'epica', true, 'player', 'MEX-04'),
(275, 'MEX', 'Mexico', 'Jesus Gallardo', 'LI', 'epica', true, 'player', 'MEX-05'),
(276, 'MEX', 'Mexico', 'Edson Alvarez', 'MC', 'rara', true, 'player', 'MEX-06'),
(277, 'MEX', 'Mexico', 'Luis Chavez', 'MC', 'rara', true, 'player', 'MEX-07'),
(278, 'MEX', 'Mexico', 'Orbelin Pineda', 'MC', 'rara', true, 'player', 'MEX-08'),
(279, 'MEX', 'Mexico', 'Hirving Lozano', 'ED', 'rara', true, 'player', 'MEX-09'),
(280, 'MEX', 'Mexico', 'Santiago Gimenez', 'DC', 'rara', true, 'player', 'MEX-10'),
(281, 'MEX', 'Mexico', 'Julian Quinones', 'EI', 'rara', true, 'player', 'MEX-11'),
(282, 'MEX', 'Mexico', 'Julio Gonzalez', 'ARQ', 'comun', false, 'player', 'MEX-12'),
(283, 'MEX', 'Mexico', 'Raul Rangel', 'ARQ', 'comun', false, 'player', 'MEX-13'),
(284, 'MEX', 'Mexico', 'Kevin Alvarez', 'DEF', 'comun', false, 'player', 'MEX-14'),
(285, 'MEX', 'Mexico', 'Jesus Orozco', 'DEF', 'comun', false, 'player', 'MEX-15'),
(286, 'MEX', 'Mexico', 'Victor Guzman', 'DEF', 'comun', false, 'player', 'MEX-16'),
(287, 'MEX', 'Mexico', 'Gerardo Arteaga', 'DEF', 'comun', false, 'player', 'MEX-17'),
(288, 'MEX', 'Mexico', 'Israel Reyes', 'DEF', 'comun', false, 'player', 'MEX-18'),
(289, 'MEX', 'Mexico', 'Carlos Rodriguez', 'MED', 'comun', false, 'player', 'MEX-19'),
(290, 'MEX', 'Mexico', 'Erick Sanchez', 'MED', 'comun', false, 'player', 'MEX-20'),
(291, 'MEX', 'Mexico', 'Marcel Ruiz', 'MED', 'comun', false, 'player', 'MEX-21'),
(292, 'MEX', 'Mexico', 'Luis Romo', 'MED', 'comun', false, 'player', 'MEX-22'),
(293, 'MEX', 'Mexico', 'Uriel Antuna', 'DEL', 'comun', false, 'player', 'MEX-23'),
(294, 'MEX', 'Mexico', 'Raul Jimenez', 'DEL', 'comun', false, 'player', 'MEX-24'),
(295, 'MEX', 'Mexico', 'Cesar Huerta', 'DEL', 'comun', false, 'player', 'MEX-25'),
(296, 'MEX', 'Mexico', 'Roberto Alvarado', 'DEL', 'comun', false, 'player', 'MEX-26'),
(297, 'MEX', 'Mexico', 'Javier Aguirre', 'DT', 'legendaria', true, 'coach', 'MEX-27'),
(298, 'MAR', 'Marruecos', 'Yassine Bounou', 'ARQ', 'epica', true, 'player', 'MAR-01'),
(299, 'MAR', 'Marruecos', 'Achraf Hakimi', 'LD', 'epica', true, 'player', 'MAR-02'),
(300, 'MAR', 'Marruecos', 'Nayef Aguerd', 'DFC', 'epica', true, 'player', 'MAR-03'),
(301, 'MAR', 'Marruecos', 'Romain Saiss', 'DFC', 'epica', true, 'player', 'MAR-04'),
(302, 'MAR', 'Marruecos', 'Noussair Mazraoui', 'LI', 'epica', true, 'player', 'MAR-05'),
(303, 'MAR', 'Marruecos', 'Sofyan Amrabat', 'MC', 'rara', true, 'player', 'MAR-06'),
(304, 'MAR', 'Marruecos', 'Azzedine Ounahi', 'MC', 'rara', true, 'player', 'MAR-07'),
(305, 'MAR', 'Marruecos', 'Bilal El Khannouss', 'MC', 'rara', true, 'player', 'MAR-08'),
(306, 'MAR', 'Marruecos', 'Brahim Diaz', 'ED', 'rara', true, 'player', 'MAR-09'),
(307, 'MAR', 'Marruecos', 'Youssef En-Nesyri', 'DC', 'rara', true, 'player', 'MAR-10'),
(308, 'MAR', 'Marruecos', 'Abde Ezzalzouli', 'EI', 'rara', true, 'player', 'MAR-11'),
(309, 'MAR', 'Marruecos', 'Munir Mohamedi', 'ARQ', 'comun', false, 'player', 'MAR-12'),
(310, 'MAR', 'Marruecos', 'El Mehdi Benabid', 'ARQ', 'comun', false, 'player', 'MAR-13'),
(311, 'MAR', 'Marruecos', 'Chadi Riad', 'DEF', 'comun', false, 'player', 'MAR-14'),
(312, 'MAR', 'Marruecos', 'Jawad El Yamiq', 'DEF', 'comun', false, 'player', 'MAR-15'),
(313, 'MAR', 'Marruecos', 'Yahya Attiyat Allah', 'DEF', 'comun', false, 'player', 'MAR-16'),
(314, 'MAR', 'Marruecos', 'Adam Aznou', 'DEF', 'comun', false, 'player', 'MAR-17'),
(315, 'MAR', 'Marruecos', 'Abdelhamid Sabiri', 'DEF', 'comun', false, 'player', 'MAR-18'),
(316, 'MAR', 'Marruecos', 'Selim Amallah', 'MED', 'comun', false, 'player', 'MAR-19'),
(317, 'MAR', 'Marruecos', 'Amir Richardson', 'MED', 'comun', false, 'player', 'MAR-20'),
(318, 'MAR', 'Marruecos', 'Ismael Saibari', 'MED', 'comun', false, 'player', 'MAR-21'),
(319, 'MAR', 'Marruecos', 'Reda Belahyane', 'MED', 'comun', false, 'player', 'MAR-22'),
(320, 'MAR', 'Marruecos', 'Hakim Ziyech', 'DEL', 'comun', false, 'player', 'MAR-23'),
(321, 'MAR', 'Marruecos', 'Soufiane Rahimi', 'DEL', 'comun', false, 'player', 'MAR-24'),
(322, 'MAR', 'Marruecos', 'Ayoub El Kaabi', 'DEL', 'comun', false, 'player', 'MAR-25'),
(323, 'MAR', 'Marruecos', 'Eliesse Ben Seghir', 'DEL', 'comun', false, 'player', 'MAR-26'),
(324, 'MAR', 'Marruecos', 'Mohamed Ouahbi', 'DT', 'legendaria', true, 'coach', 'MAR-27')
on conflict (id) do update set
  team_code = excluded.team_code,
  team_name = excluded.team_name,
  player_name = excluded.player_name,
  position = excluded.position,
  rarity = excluded.rarity,
  is_starter = excluded.is_starter,
  role = excluded.role,
  number_code = excluded.number_code;
